# Generated by Django 5.0.14 on 2026-03-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_file_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='book',
            new_name='catalog_boo_provide_ff9bcc_idx',
            old_name='catalog_boo_provider_ae7d2c_idx',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='catalog_boo_grade_7ea629_idx',
            old_name='catalog_boo_grade_6d3b60_idx',
        ),
    ]
